name:
on:
  push:
    branchnes:
      - main
    pull_request:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      
      - name: set up gcc
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: x64
       
      - name: run tests
        run: make test

